### ISSUE TITLE
nvidia-smi doesn't work on the macleod cluster. 

### ISSUE THREAD

**Issue by kaminocode** [AidenDurrant/abdn-hpc#1]
$ nvidia-smi
bash: nvidia-smi: command not found

nvidia-smi gives the above output. How do you check GPU memory allocation on macleod cluster?

**Comment by AidenDurrant** [comment]
Hi,

To view the GPU allocation you must first import the cuda modules to access the command `module load cudatoolkit-<version>` then you can run `nvidia-smi`.

Additionally, you must have requested the GPU nodes via SLURM in order to see the allocation. The login node does not contain any GPUs therefore will not provide you with any information. Adjusting the SLURM script as follows will provide what you are after.

Also note that each GPU you select has approximately 5.7GB of VRAM so if you allocate `gpu:7` you are accessing 7 of these 5.7GB GPU's.

```
#!/bin/bash
#SBATCH --nodes=1 # number of nodes
#SBATCH --cpus-per-task=12 # number of cores
#SBATCH --mem=32G # memory pool for all cores

#SBATCH --ntasks-per-node=1 # one job per node
#SBATCH --gres=gpu:7 # 7 of the 21 partitions
#SBATCH --partition=gpu

#SBATCH -o slurm.%j.out # STDOUT
#SBATCH -e slurm.%j.err # STDERR

#SBATCH --mail-type=ALL 
#SBATCH --mail-user=<username>@abdn.ac.uk 

module load cudatoolkit-<version>
nvidia-smi

module load anaconda3
source activate test

srun python example_script.py --epochs=25 --save /home/<username>/sharedscratch/
```
